final List<Map<String, dynamic>> basisProducten = [
    {"naam": "Brood", "dagen": 1, "bediening": false, "categorie": "Lunch"},
    {"naam": "Burger brood", "dagen": 1, "bediening": false},
    {"naam": "Knoflooksaus", "dagen": 6, "bediening": false},
    {"naam": "Kruidenboter", "dagen": 10, "bediening": false},
    {"naam": "Gegr. Champ", "dagen": 4, "bediening": false},
    {"naam": "Cheddar geraspt", "dagen": 7, "bediening": false},
    {"naam": "Mozzarella", "dagen": 5, "bediening": false},
    {"naam": "Serranoham", "dagen": 7, "bediening": false},
    {"naam": "Oosters plateau", "dagen": 60, "bediening": false},
    {"naam": "Wakame", "dagen": 2, "bediening": false},
    {"naam": "Chilisaus", "dagen": 27, "bediening": false},
    {"naam": "Carpaccio", "dagen": 2, "bediening": false},
    {"naam": "Carpaccio kaas", "dagen": 7, "bediening": false},
    {"naam": "Gefrituurde uitjes", "dagen": 20, "bediening": false},
    {"naam": "Zongedroogde tomaat", "dagen": 7, "bediening": false},
    {"naam": "Truffelmayo", "dagen": 27, "bediening": false},
    {"naam": "Nachos", "dagen": 7, "bediening": false},
    {"naam": "Pulled chicken", "dagen": 5, "bediening": false},
    {"naam": "Tomatensoep", "dagen": 3, "bediening": false},
    {"naam": "Slagroom", "dagen": 2, "bediening": true},
    {"naam": "Soepballen", "dagen": 3, "bediening": false},
    {"naam": "Schnitzel", "dagen": 1, "bediening": false},
    {"naam": "Boerengarn.", "dagen": 4, "bediening": false},
    {"naam": "Pepersaus", "dagen": 3, "bediening": false},
    {"naam": "Champ roomsaus", "dagen": 3, "bediening": false},
    {"naam": "Citroenen", "dagen": 2, "bediening": true},
    {"naam": "Limoen", "dagen": 2, "bediening": true},
    {"naam": "Sinasappel", "dagen": 2, "bediening": true},
    {"naam": "Glaze", "dagen": 7, "bediening": false},
    {"naam": "Chimichuri", "dagen": 7, "bediening": false},
    {"naam": "Groente", "dagen": 1, "bediening": false},
    {"naam": "Sesamzaad", "dagen": 30, "bediening": false},
    {"naam": "Gambas", "dagen": 1, "bediening": false},
    {"naam": "Quiche", "dagen": 3, "bediening": false},
    {"naam": "Crème fraîche", "dagen": 4, "bediening": false},
    {"naam": "Cheddar", "dagen": 7, "bediening": false},
    {"naam": "Spies 200", "dagen": 2, "bediening": false},
    {"naam": "Spies 150", "dagen": 2, "bediening": false},
    {"naam": "Friet", "dagen": 1, "bediening": false},
    {"naam": "Roseval", "dagen": 3, "bediening": false},
    {"naam": "Sla", "dagen": 1, "bediening": false},
    {"naam": "Tomaat", "dagen": 2, "bediening": false},
    {"naam": "Komkommer", "dagen": 2, "bediening": false},
    {"naam": "Rode ui", "dagen": 3, "bediening": false},
    {"naam": "Honing mosterd", "dagen": 28, "bediening": false},
    {"naam": "Balsamicodressing", "dagen": 31, "bediening": false},
    {"naam": "Cocktailsaus", "dagen": 30, "bediening": false},
    {"naam": "Geitenkaas", "dagen": 10, "bediening": false},
    {"naam": "Walnoten", "dagen": 30, "bediening": false},
    {"naam": "Vijgen", "dagen": 4, "bediening": false},
    {"naam": "Burgers", "dagen": 5, "bediening": false},
    {"naam": "Burgerrelish", "dagen": 27, "bediening": false},
    {"naam": "Augurk", "dagen": 7, "bediening": false},
    {"naam": "Bacon", "dagen": 7, "bediening": false},
    {"naam": "Creamy baconsaus", "dagen": 27, "bediening": false},
    {"naam": "Kipburgers", "dagen": 33, "bediening": false},
    {"naam": "Tzatziki", "dagen": 5, "bediening": false},
    {"naam": "Avocado burgers", "dagen": 33, "bediening": false},
    {"naam": "Smokey hemp saus", "dagen": 29, "bediening": false},
    {"naam": "Ham", "dagen": 2, "bediening": false},
    {"naam": "Kaas", "dagen": 2, "bediening": false},
    {"naam": "Eiersalade", "dagen": 4, "bediening": false},
    {"naam": "Brandermayo", "dagen": 28, "bediening": false},
    {"naam": "Kroketten", "dagen": 35, "bediening": false},
    {"naam": "Mosterd", "dagen": 30, "bediening": false},
    {"naam": "Tonijnsalade", "dagen": 3, "bediening": false},
    {"naam": "Curry", "dagen": 27, "bediening": false},
    {"naam": "Kipfilet", "dagen": 2, "bediening": false},
    {"naam": "Bitterballen", "dagen": 37, "bediening": false},
    {"naam": "Advocaatsaus", "dagen": 30, "bediening": false},
    {"naam": "Monchou", "dagen": 3, "bediening": false},
    {"naam": "Bastogne", "dagen": 10, "bediening": true},
    {"naam": "Kersen", "dagen": 4, "bediening": false},
    {"naam": "Choco saus", "dagen": 30, "bediening": false},
    {"naam": "Lava cake", "dagen": 10, "bediening": false},
    {"naam": "Rood fruit", "dagen": 5, "bediening": false},
    {"naam": "Aardbeisaus", "dagen": 29, "bediening": true},
    {"naam": "Karamelsaus", "dagen": 39, "bediening": true},
    {"naam": "Monchou bediening", "dagen": 1, "bediening": true},
    {"naam": "Munt", "dagen": 2, "bediening": true},
    {"naam": "Melk", "dagen": 3, "bediening": true},
    {"naam": "Macarons", "dagen": 5, "bediening": true},
    {"naam": "Pancakes", "dagen": 15, "bediening": false},
    {"naam": "Peterselie", "dagen": 1, "bediening": false},
    {"naam": "China rose", "dagen": 1, "bediening": false},
    {"naam": "Espresso Martini", "dagen": 30, "bediening": true},
    {"naam": "Pornstar Martini", "dagen": 30, "bediening": true},
    {"naam": "Kletskoppen", "dagen": 15, "bediening": false},
    {"naam": "Cheesecake", "dagen": 4, "bediening": false},
    {"naam": "Kip gebakken", "dagen": 2, "bediening": false},
    {"naam": "Fruit Coulis", "dagen": 5, "bediening": false},
    {"naam": "Gember", "dagen": 2, "bediening": true},
    {"naam": "Praline", "dagen": 4, "bediening": true},
    {"naam": "Passievrucht", "dagen": 3, "bediening": true}
  ];

final List<String> medewerkers = ["Jens", "Isa", "Tyan", "Lisa","Mik", "Marit", "Timo", "Hidde", "Jop", "Eva", "Wytze", "Bediening"];
