final List<Map<String, dynamic>> basisProducten = [
  // Warm
  {"naam": "Aardappel gratin", "dagen": 3, "categorie": "Warm"},
  {"naam": "Asperges", "dagen": 2, "categorie": "Warm"},
  {"naam": "Bacon", "dagen": 7, "categorie": "Warm"},
  {"naam": "Biefstukpuntjes", "dagen": 2, "categorie": "Warm"},
  {"naam": "Biefstukspies", "dagen": 2, "categorie": "Warm"},
  {"naam": "Boeren garn.", "dagen": 3, "categorie": "Warm"},
  {"naam": "Burger", "dagen": 5, "categorie": "Warm"},
  {"naam": "Champ saus", "dagen": 2, "categorie": "Warm"},
  {"naam": "Champingons", "dagen": 2, "categorie": "Warm"},
  {"naam": "Cheddar", "dagen": 7, "categorie": "Warm"},
  {"naam": "Chicken wings", "dagen": 4, "categorie": "Warm"},
  {"naam": "Gambas", "dagen": 1, "categorie": "Warm"},
  {"naam": "Glaze", "dagen": 7, "categorie": "Warm"},
  {"naam": "Groentes", "dagen": 2, "categorie": "Warm"},
  {"naam": "Half kippetje", "dagen": 1, "categorie": "Warm"},
  {"naam": "Pepersaus", "dagen": 2, "categorie": "Warm"},
  {"naam": "Risotto", "dagen": 2, "categorie": "Warm"},
  {"naam": "Schnitzel", "dagen": 1, "categorie": "Warm"},
  {"naam": "Spareribs", "dagen": 4, "categorie": "Warm"},
  {"naam": "Spätzle", "dagen": 3, "categorie": "Warm"},
  {"naam": "Tournedos", "dagen": 2, "categorie": "Warm"},

  // Koud
  {"naam": "Appel perzik crisp", "dagen": 3, "categorie": "Koud"},
  {"naam": "Bastogne", "dagen": 7, "categorie": "Koud"},
  {"naam": "Bierbeslag", "dagen": 2, "categorie": "Koud"},
  {"naam": "Brie", "dagen": 3, "categorie": "Koud"},
  {"naam": "Brood/burger brood", "dagen": 1, "categorie": "Koud"},
  {"naam": "Carpaccio", "dagen": 2, "categorie": "Koud"},
  {"naam": "Dillemouse", "dagen": 2, "categorie": "Koud"},
  {"naam": "Friet", "dagen": 1, "categorie": "Koud"},
  {"naam": "Gefr ui", "dagen": 7, "categorie": "Saladiere"},
  {"naam": "Gebakken spek", "dagen": 3, "categorie": "Koud"},
  {"naam": "Gambas in knoflookolie", "dagen": 2, "categorie": "Koud"},
  {"naam": "Gebakken spek", "dagen": 3, "categorie": "Koud"},
  {"naam": "Gerookte zalm", "dagen": 2, "categorie": "Koud"},
  {"naam": "Knoflooksaus", "dagen": 4, "categorie": "Koud"},
  {"naam": "Komkommer", "dagen": 2, "categorie": "Saladiere"},
  {"naam": "Parmazaan", "dagen": 4, "categorie": "Koud"},
  {"naam": "Perzikcoulis", "dagen": 3, "categorie": "Koud"},
  {"naam": "Rode ui", "dagen": 2, "categorie": "Saladiere"},
  {"naam": "Sla", "dagen": 1, "categorie": "Saladiere"},
  {"naam": "Slagroom", "dagen": 3, "categorie": "Koud"},
  {"naam": "Soep van de dag", "dagen": 2, "categorie": "Koud"},
  {"naam": "Sticky toffee pudding", "dagen": 3, "categorie": "Koud"},
  {"naam": "Tex mex", "dagen": 4, "categorie": "Koud"},
  {"naam": "Tomaat", "dagen": 2, "categorie": "Saladiere"},
  {"naam": "Tomatensoep", "dagen": 2, "categorie": "Koud"},
  {"naam": "Tonijntartaar", "dagen": 1, "categorie": "Koud"},
  {"naam": "Triffle", "dagen": 2, "categorie": "Koud"},
  {"naam": "Walnoten", "dagen": 14, "categorie": "Koud"},
  {"naam": "Zelfgemaakte truffelmayo", "dagen": 4, "categorie": "Koud"},
  {"naam": "Zon. Tomaat", "dagen": 4, "categorie": "Saladiere"},

  // Lunch
  {"naam": "Eiersalade", "dagen": 3, "categorie": "Lunch"},
  {"naam": "Ham", "dagen": 2, "categorie": "Lunch"},
  {"naam": "Kaas", "dagen": 2, "categorie": "Lunch"},
  {"naam": "Kipfilet", "dagen": 2, "categorie": "Lunch"},
  {"naam": "Tonijnsalade", "dagen": 3, "categorie": "Lunch"},
  {"naam": "Brood", "dagen": 1, "categorie": "Lunch"},

  // Vries
  {"naam": "Avocado burgers", "dagen": 30, "categorie": "Vries"},
  {"naam": "Bitterbal", "dagen": 30, "categorie": "Vries"},
  {"naam": "Frikandel", "dagen": 30, "categorie": "Vries"},
  {"naam": "Glutenvrij", "dagen": 30, "categorie": "Vries"},
  {"naam": "Hapjes", "dagen": 30, "categorie": "Vries"},
  {"naam": "Kaassoufle", "dagen": 20, "categorie": "Vries"},
  {"naam": "Kipburgers", "dagen": 30, "categorie": "Vries"},
  {"naam": "Kipnuggets", "dagen": 30, "categorie": "Vries"},
  {"naam": "Kroket", "dagen": 30, "categorie": "Vries"},
  {"naam": "Overig", "dagen": 30, "categorie": "Vries"},
  {"naam": "Pancakes", "dagen": 29, "categorie": "Vries"},
];

final List<String> medewerkers = [
  "Jens", "Isa", "Tyan", "Lisa", "Mik", "Marit", "Timo", "Hidde", "Jop", "Eva", "Wytze", "Bediening"
];